apiVersion: v1
data:
  my.cnf: "[mysqld]\npid-file\t = /var/run/mysqld/mysqld.pid\nsocket\t\t = /var/run/mysqld/mysqld.sock\ndatadir\t\t
    = /var/lib/mysql\nbind-address = 0.0.0.0"
kind: ConfigMap
metadata:
  creationTimestamp: null
  namespace: opsmon
  name: mycnf
