apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: n9e-mysql
  namespace: opsmon
spec:
  type: NodePort
  selector:
    app: n9e-mysql
  ports:
  - name: http
    port: 3306
    targetPort: 3306
    nodePort: 31306

