apiVersion: v1
kind: Service
metadata:
  name: ibex
  labels:
    app: n9e-ibex
  namespace: opsmon
spec:
  type: NodePort
  selector:
    app: n9e-ibex
  ports:
  - name: http1
    port: 10090
    targetPort: 10090
    nodePort: 31090
  - name: http2
    port: 20090
    targetPort: 20090
    nodePort: 32090

