apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: opsmon
spec:
  selector:
    matchLabels:
      app: n9e-telegraf
      version: "1.20.3"
  template:
    metadata:
      labels:
        app: n9e-telegraf
        version: "1.20.3"
    spec:
      containers:
      - name: n9e-telegraf
        image: telegraf:1.20.3
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 10"]
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8125
        - containerPort: 8092
        - containerPort: 8094
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
      volumes:
      - name: telegraf-config
        configMap: 
          name: telegraf-config

