apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: n9e-telegraf
  namespace: opsmon
spec:
  type: NodePort
  selector:
    app: n9e-telegraf
  ports:
  - name: http1
    port: 8125
    targetPort: 8125
    nodePort: 31125
  - name: http2
    port: 8092
    targetPort: 8092
    nodePort: 31092
  - name: http3
    port: 8094
    targetPort: 8094
    nodePort: 31094
