---

- name: Prometheus | Create manifests dir
  file:
    path: "{{ kube_config_dir }}/addons/kube-prometheus/manifests"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Prometheus | Create setup dir
  file:
    path: "{{ kube_config_dir }}/addons/kube-prometheus/manifests/setup"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: copy files
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ kube_config_dir }}/addons/kube-prometheus/manifests/"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: Deploy
  shell: "{{ bin_dir }}/kubectl apply --server-side -f {{ kube_config_dir }}/addons/kube-prometheus/manifests/setup/"
  ignore_errors: true
  when:
    - inventory_hostname == groups['kube_control_plane'][0]


- name: Sleep 5s
  wait_for:
    timeout: 5


- name: Deploy prometheus
  shell: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/addons/kube-prometheus/manifests/"
  ignore_errors: true
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
