apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: opsmon
spec:
  minReadySeconds: 1
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: n9e-redis
      version: "6.2"
  template:
    metadata:
      labels:
        app: n9e-redis
        version: "6.2"
    spec:
      containers:
      - name: n9e-fe
        image: redis:6.2
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 10"]
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

