apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: n9e-redis
  namespace: opsmon
spec:
  type: NodePort
  selector:
    app: n9e-redis
  ports:
  - name: http
    port: 6379
    targetPort: 6379
    nodePort: 31379

