---
- name: Check ansible version
  import_playbook: ansible_version.yml

- hosts: k8s_cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: yes
  roles:
    - { role: cluster-storage/nfs }
