apiVersion: v1
kind: Service
metadata:
  name: nserver
  labels:
    app: n9e-server
    app.kubernetes.io/name: nserver-exporter
  namespace: opsmon
spec:
  selector:
    app: n9e-server
  ports:
  - name: http
    port: 19000
    targetPort: 19000
