apiVersion: v1
kind: Service
metadata:
  name: nwebapi
  labels:
    app: n9e-webapi
    app.kubernetes.io/name: nwebapi-exporter
  namespace: opsmon
spec:
  type: NodePort
  selector:
    app: n9e-webapi
  ports:
  - name: http
    port: 18000
    targetPort: 18000
    nodePort: 31800
