---
- name: Refresh Time Fact
  setup: filter=ansible_date_time

- name: Set Backup Directory
  set_fact:
    etcd_backup_directory: "/etc/kubernetes/backup/etcd"

- name: Create Backup Directory
  file:
    path: "{{ etcd_backup_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Backup etcd v3 data
  command: >-
    {{ bin_dir }}/etcdctl
      snapshot save {{ etcd_backup_directory }}/{{ etcd_snapshot_name }} --cacert={{ etcd_cert_dir }}/ca.pem --cert={{ etcd_cert_dir }}/admin-{{ inventory_hostname }}.pem --key={{ etcd_cert_dir }}/admin-{{ inventory_hostname }}-key.pem
  retries: 3
  register: etcd_backup_v3_command

- name: Fetch backup file
  fetch:
    src: "{{ etcd_backup_directory }}/{{ etcd_snapshot_name }}"
    dest: "/var/ko/data/backup/{{ cluster_name }}/{{ etcd_snapshot_name }}"
    flat: yes

- name: Remove etcd temp backup file
  file:
    name: "/etc/kubernetes/backup/etcd/{{ etcd_snapshot_name }}"
    state: absent

