apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentd
  namespace: opsmon
spec:
  minReadySeconds: 1
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: n9e-agentd
      version: "0.2"
  template:
    metadata:
      labels:
        app: n9e-agentd
        version: "0.2"
    spec:
      containers:
      - name: n9e-agentd
        image: ulric2019/ibex:0.2
        imagePullPolicy: Always
        command:
          - "/app/ibex"
          - "agentd"
        env:
        - name: GIN_MODE
          value: release
        - name: TZ
          value: Asia/Shanghai
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 10"]
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: ibexetc
          mountPath: /app/etc
      volumes:
      - name: ibexetc
        configMap: 
          name: ibexetc

